# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Training Data Lab
email: bastian.gonzalezbustamante@politics.ox.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  This project focuses on labelling data until getting a reliable set to train models for social sciences research projects. Then, we classify larger amounts of data using trained models backed by human validation workflow. The latter improves the AI and machine learning processes.
baseurl: "/training-datalab.com"
url: "https://training-datalab.github.io"

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

